#!/bin/sh
read rawPreRecieveInfo
IFS=' ' read -ra preRecieveInfo <<< "$rawPreRecieveInfo"
IFS=''

COMMIT_HASH=${preRecieveInfo[1]}
COMMIT_BRANCH=${preRecieveInfo[2]}
COMMIT_AUTHOR=$(git log -1 $COMMIT_HASH --pretty=%ce)
COMMIT_MSG=$(git log -1 $COMMIT_HASH --pretty=%B)

python hooks/scripts/pre-receive.py ${COMMIT_BRANCH} ${COMMIT_HASH} ${COMMIT_AUTHOR} ${COMMIT_MSG}