cmake_minimum_required(VERSION 3.15)

# Some remarks to remove
# SomeLib - project compiled unit name
# SOMELIB - project macro for CMake

project(
    SomeLibLibProject
    LANGUAGES CXX
    VERSION 0.1.0
)

option(SOMELIB_BUILD_STATIC "Build SomeLib module as static lib" ON)
option(SOMELIB_BUILD_SAMPLES "Build SomeLib sample projects" ON)
option(SOMELIB_BUILD_UTESTS "Build SomeLib unit test for lib" OFF)
option(SOMELIB_ENABLE_MACROS "Enable SomeLib macros to do simple logger usage" OFF)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/lib)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)

set(SOMELIB_EXPORT_MACRO SOMELIB_EXPORT)
set(SOMELIB_EXPORT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/include/SomeLib/generated)
set(SOMELIB_EXPORT_FILE ${CMAKE_CURRENT_SOURCE_DIR}/include/SomeLib/generated/threadpool_export.h)

# paths
set(
    SOMELIB_INCLUDE_PATH
    include/SomeLib
    src
    src/storage
)

# sources
set( 
    SOMELIB_SHARED_HEADERS
    SomeLib/Header1.h
	SomeLib/Header2.h
    SomeLib/HeaderN.h
)
list(TRANSFORM SOMELIB_SHARED_HEADERS PREPEND include/SomeLib/)
list(APPEND SOMELIB_SHARED_HEADERS ${SOMELIB_EXPORT_FILE} include/SomeLubUnionHeader.h)

set(
    SOMELIB_SRC_FILES
	export/Header1.cpp
	export/Header2.cpp
	export/HeaderN.cpp
	internal/InternalUnit.cpp
	internal/InternalUnit.h
)
list(TRANSFORM SOMELIB_SRC_FILES PREPEND src/)

# compiled unit
if(${SOMELIB_BUILD_STATIC})
    message(STATUS "SomeLib lib configured as static lib")
    add_library(SomeLib STATIC)
else()
    message(STATUS "SomeLib lib configured as dynamic lib")
    add_library(SomeLib SHARED)
endif()
add_library(libs::SomeLib ALIAS SomeLib)

# generated by CMake utils
include(GenerateExportHeader)
generate_export_header(
    SomeLib
    EXPORT_MACRO_NAME ${SOMELIB_EXPORT_MACRO}
    EXPORT_FILE_NAME  ${SOMELIB_EXPORT_FILE}
)

# links
target_include_directories(SomeLib PUBLIC "include")

target_include_directories(SomeLib PRIVATE ${SOMELIB_INCLUDE_PATH})
target_sources(
    SomeLib
    PRIVATE
    ${SOMELIB_SRC_FILES}
    ${SOMELIB_SHARED_HEADERS}
)

# options
if (${SOMELIB_BUILD_SAMPLES})
    message(STATUS "Start configure samples for SomeLib Library")
    add_subdirectory(samples)
endif()

if(${SOMELIB_BUILD_UTESTS})
    message(WARNING "Unit test for SomeLib Library is not supported on this version")
    # add_subdirectory(tests)
endif()

if(${SOMELIB_ENABLE_MACROS})
    target_compile_definitions(SomeLib PUBLIC "MACROS") # todo: add custom defined macros names
endif()

